### ISSUE TITLE
validation not performed when charset is in content-type

### ISSUE THREAD

**Issue by amplexdenmark** [elixir-oasis/oasis#15]
Hi

When I do a POST to a generated function having "Content-type: application/json" the validation of the body is performed as expected.

But if it is "Content-type: application/json; charset=utf-8" the validation is not performed at all.

The reason is that line 139 in request_validator returns %{} and therefore nil is returned from schema_by_request_content_type

I guess the charset information should be stripped before doing the Map lookup

Best regards

**Comment by xinz** [comment]
Hello @amplexdenmark , thanks for your report, there is a fixing to this issue, could you please double check use the `main` branch?

**Comment by amplexdenmark** [comment]
I am on 0.5.0. ie. mix.exs refers to {:oasis, "~> 0.5"}
But I just realised that I have not re-run the stub creation since 0.3.0, guess I need to do that, right?

**Comment by amplexdenmark** [comment]
Ahh, I misunderstood, you just fixed it. I will refer my mix.exs to the use the main branch. Thank you for the quick fix.

**Comment by amplexdenmark** [comment]
The fix did not solve this issue.

Line 139 in `Oasis.Plug.RequestValidator` still assigns `%{}` to `matched`
Leading to `matched_schema` being `nil` in line 94.
Leading to validation not being performed as it matches `parse_and_validate!(_, _, _, value)` in Oasis.Validator

**Comment by xinz** [comment]
@amplexdenmark yes, thanks very much! There is another commit to fix issue, could you please take a check with `main` branch again?

**Comment by amplexdenmark** [comment]
Yes, this fixes the issue. Thank you!

**Comment by xinz** [comment]
Thanks for your confirmation, let's wait a moment to see whether still something need to fix into the package release.

**Comment by xinz** [comment]
Released in [0.5.1](https://hex.pm/packages/oasis/0.5.1)
