### ISSUE TITLE
JWT Support

### ISSUE THREAD

**Issue by hou8** [elixir-oasis/oasis#2]
# JWT Support

## 背景

- Web API 场景下一定会需要授权鉴权的场景, 而 JWT 是一个比较常见且通用的鉴权方案
- 因此将 JWT 的支持加在 oasis 中也是一个比较自然的想法
- 同时 OAS 自身规定了的 JWT 鉴权的相关 Spec, 基于这种约定也可以做到比较好的使用体验

## 使用场景

1. 作为工具函数:
    1. 生成 Token
    2. 验证 Token
2. 作为 Plug:
    1. 根据 OAS 的标准定义, 从相应的 HTTP Header 中找到对应的 token 并鉴定 
3. 根据 OAS 定义, 从相应的 path 中查看是否需要鉴权, 如果需要, 则在对应的自动生成代码中添加第 2 步的 plug 调用

**Comment by xinz** [comment]
Closed via https://github.com/elixir-oasis/oasis/pull/5
